name: notion build

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: generate notion pages
        run: |
          npm i -g notablog
          notablog generate .
              - name: Commit update
      - name: update repo
        run: |
          git config --global user.name 'notion builder'
          git config --global user.email 'me@yiu.ch'
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git commit -am "generated notion pages" && git push || echo "no changes to commit"
        env:
          CI: true
